=== LavrentevaAlexandra/Task5.0/files/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/flowers"
        xmlns:tns="http://www.example.com/flowers"
        elementFormDefault="qualified">
    <element name="flowers">
        <complexType>
            <sequence>
                <element ref="tns:flower"
                         minOccurs="2"
                         maxOccurs="unbounded" />
            </sequence>
        </complexType>
    </element>

    <element name="flower" type="tns:Flower" abstract="true"/>
    <element name="poisonous-flower" type="tns:PoisonousFlower" substitutionGroup="tns:flower"/>
    <element name="rare-flower" type="tns:RareFlower" substitutionGroup="tns:flower"/>
    
    <complexType name="Flower">
        <sequence>
            <element name="soil">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="podzolic"/>        <!--подзолистая-->
                        <enumeration value="dirt"/>            <!--грунтовая-->
                        <enumeration value="sod-podzolic"/>    <!--дерново-подзолистая-->
                    </restriction>
                </simpleType>
            </element>
            <element name="origin" type="string" />
            <element name="visual-parameters" type="tns:VisualParameters" />
            <element name="growing-tips" type="tns:GrowingTips" />
            <element name="multiplying">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="leaf"/>             <!--листья-->
                        <enumeration value="stalk"/>            <!--черенки-->
                        <enumeration value="seed"/>             <!--семена-->
                    </restriction>
                </simpleType>
            </element>
        </sequence>

        <attribute name="id" type="tns:Id" use="required" />
        <attribute name="name" type="string" use="optional" default="no name"/>
    </complexType>

    <complexType name="PoisonousFlower" >
        <complexContent>
            <extension base="tns:Flower">
                <sequence>
                    <element name="poisonous-part" type="tns:PoisonousElement"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="RareFlower" >
        <complexContent>
            <extension base="tns:Flower">
                <sequence>
                    <element name="quantity" type="integer"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>


    <simpleType name="Id">
        <restriction base="ID">
            <pattern value="[a-zA-Z]{6}"/>
        </restriction>
    </simpleType>

    <complexType name="VisualParameters">
        <sequence>
            <element name="stem-colour" type="string" />
            <element name="leaf-colour" type="string" />
            <element name="average-size" type="double" />
        </sequence>
    </complexType>

    <complexType name="GrowingTips">
        <sequence>
            <element name="temperature" type="integer" />            <!--in degrees-->
            <element name="photophilous" type="boolean" />
            <element name="watering-amount" type="tns:WaterAmount" />    <!--ml per week-->
        </sequence>
    </complexType>

    <simpleType name="Temperature">
        <restriction base="integer" >
            <minInclusive value="15"/>
            <maxInclusive value="25"/>
        </restriction>
    </simpleType>

    <simpleType name="WaterAmount">
        <restriction base="integer" >
            <minInclusive value="100"/>
            <maxInclusive value="700"/>
        </restriction>
    </simpleType>

    <simpleType name="PoisonousElement">
        <restriction base="string">
            <enumeration value="all parts"/>
            <enumeration value="leaf"/>
            <enumeration value="bulb"/>
            <enumeration value="seed"/>
            <enumeration value="juice"/>
            <enumeration value="root"/>
        </restriction>
    </simpleType>
    
</schema>

=== LavrentevaAlexandra/Task5.0/files/flowers.xml
<?xml version="1.0" encoding="UTF-8"?>
<flowers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.example.com/flowers"
         xsi:schemaLocation="http://www.example.com/flowers schema.xsd">
    <poisonous-flower id="AAAAAA" name="Lily">
        <soil>podzolic</soil>
        <origin>Asia</origin>
        <visual-parameters>
            <stem-colour>Green</stem-colour>
            <leaf-colour>Green</leaf-colour>
            <average-size>30</average-size>
        </visual-parameters>
        <growing-tips>
            <temperature>20</temperature>
            <photophilous>true</photophilous>
            <watering-amount>450</watering-amount>
        </growing-tips>
        <multiplying>seed</multiplying>
        <poisonous-part>bulb</poisonous-part>
    </poisonous-flower>
    <rare-flower id="BBBBBB" name="Cosmea">
        <soil>dirt</soil>
        <origin>Mexico</origin>
        <visual-parameters>
            <stem-colour>Green</stem-colour>
            <leaf-colour>Brown</leaf-colour>
            <average-size>12</average-size>
        </visual-parameters>
        <growing-tips>
            <temperature>18</temperature>
            <photophilous>true</photophilous>
            <watering-amount>300</watering-amount>
        </growing-tips>
        <multiplying>seed</multiplying>
        <quantity>230</quantity>
    </rare-flower>
    <poisonous-flower id="CCCCCC" name="may-lily">
        <soil>sod-podzolic</soil>
        <origin>Caucasus</origin>
        <visual-parameters>
            <stem-colour>Green</stem-colour>
            <leaf-colour>White</leaf-colour>
            <average-size>10</average-size>
        </visual-parameters>
        <growing-tips>
            <temperature>15</temperature>
            <photophilous>true</photophilous>
            <watering-amount>250</watering-amount>
        </growing-tips>
        <multiplying>stalk</multiplying>
        <poisonous-part>all parts</poisonous-part>
    </poisonous-flower>
    <rare-flower id="DDDDDD" name="may-lily">
        <soil>sod-podzolic</soil>
        <origin>China</origin>
        <visual-parameters>
            <stem-colour>Green</stem-colour>
            <leaf-colour>White</leaf-colour>
            <average-size>10</average-size>
        </visual-parameters>
        <growing-tips>
            <temperature>15</temperature>
            <photophilous>true</photophilous>
            <watering-amount>250</watering-amount>
        </growing-tips>
        <multiplying>stalk</multiplying>
        <quantity>10060</quantity>
    </rare-flower>
    <poisonous-flower id="EEEEEE" name="Tulip">
        <soil>podzolic</soil>
        <origin>Asia</origin>
        <visual-parameters>
            <stem-colour>Green</stem-colour>
            <leaf-colour>Green</leaf-colour>
            <average-size>25</average-size>
        </visual-parameters>
        <growing-tips>
            <temperature>22</temperature>
            <photophilous>true</photophilous>
            <watering-amount>340</watering-amount>
        </growing-tips>
        <multiplying>stalk</multiplying>
        <poisonous-part>bulb</poisonous-part>
    </poisonous-flower>
    <rare-flower id="FFFFFF" name="Scilla">
        <soil>dirt</soil>
        <origin>Siberia</origin>
        <visual-parameters>
            <stem-colour>Green</stem-colour>
            <leaf-colour>Violet</leaf-colour>
            <average-size>30</average-size>
        </visual-parameters>
        <growing-tips>
            <temperature>15</temperature>
            <photophilous>true</photophilous>
            <watering-amount>210</watering-amount>
        </growing-tips>
        <multiplying>seed</multiplying>
        <quantity>807</quantity>
    </rare-flower>
    <poisonous-flower id="GGGGGG" name="Milfoil">
        <soil>podzolic</soil>
        <origin>Russia</origin>
        <visual-parameters>
            <stem-colour>Green</stem-colour>
            <leaf-colour>White</leaf-colour>
            <average-size>47</average-size>
        </visual-parameters>
        <growing-tips>
            <temperature>18</temperature>
            <photophilous>true</photophilous>
            <watering-amount>400</watering-amount>
        </growing-tips>
        <multiplying>seed</multiplying>
        <poisonous-part>leaf</poisonous-part>
    </poisonous-flower>
    <rare-flower id="HHHHHH" name="Forget-me-not">
        <soil>podzolic</soil>
        <origin>England</origin>
        <visual-parameters>
            <stem-colour>Green</stem-colour>
            <leaf-colour>Blue</leaf-colour>
            <average-size>7</average-size>
        </visual-parameters>
        <growing-tips>
            <temperature>15</temperature>
            <photophilous>true</photophilous>
            <watering-amount>300</watering-amount>
        </growing-tips>
        <multiplying>seed</multiplying>
        <quantity>690</quantity>
    </rare-flower>
    <poisonous-flower id="IIIIII" name="Begonia">
        <soil>sod-podzolic</soil>
        <origin>India</origin>
        <visual-parameters>
            <stem-colour>Green</stem-colour>
            <leaf-colour>Pink</leaf-colour>
            <average-size>8</average-size>
        </visual-parameters>
        <growing-tips>
            <temperature>18</temperature>
            <photophilous>true</photophilous>
            <watering-amount>230</watering-amount>
        </growing-tips>
        <multiplying>seed</multiplying>
        <poisonous-part>all parts</poisonous-part>
    </poisonous-flower>
    <rare-flower id="JJJJJJ" name="Ornithogalum">
        <soil>sod-podzolic</soil>
        <origin>Africa</origin>
        <visual-parameters>
            <stem-colour>Green</stem-colour>
            <leaf-colour>White</leaf-colour>
            <average-size>20</average-size>
        </visual-parameters>
        <growing-tips>
            <temperature>25</temperature>
            <photophilous>true</photophilous>
            <watering-amount>400</watering-amount>
        </growing-tips>
        <multiplying>seed</multiplying>
        <quantity>39000</quantity>
    </rare-flower>
    <poisonous-flower id="KKKKKK" name="Cow parsnip">
        <soil>dirt</soil>
        <origin>exSSSR</origin>
        <visual-parameters>
            <stem-colour>Green</stem-colour>
            <leaf-colour>White</leaf-colour>
            <average-size>400</average-size>
        </visual-parameters>
        <growing-tips>
            <temperature>18</temperature>
            <photophilous>true</photophilous>
            <watering-amount>200</watering-amount>
        </growing-tips>
        <multiplying>seed</multiplying>
        <poisonous-part>all parts</poisonous-part>
    </poisonous-flower>
    <rare-flower id="LLLLLL" name="Gagea">
        <soil>sod-podzolic</soil>
        <origin>Africa</origin>
        <visual-parameters>
            <stem-colour>Green</stem-colour>
            <leaf-colour>Yellow</leaf-colour>
            <average-size>37</average-size>
        </visual-parameters>
        <growing-tips>
            <temperature>25</temperature>
            <photophilous>true</photophilous>
            <watering-amount>300</watering-amount>
        </growing-tips>
        <multiplying>seed</multiplying>
        <quantity>730</quantity>
    </rare-flower>
</flowers>
